# Generated by Django 4.0.3 on 2022-07-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название статьи')),
                ('full_text', models.TextField(verbose_name='Текст')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('artimage', models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='Мини-изображение')),
                ('main_article', models.BooleanField(default=False, verbose_name='Главная статья')),
                ('image_central', models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='Центральное изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
