# Generated by Django 4.0.3 on 2022-07-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название картинки')),
                ('artimage', models.ImageField(blank=True, null=True, upload_to='upload/static/img/home', verbose_name='изображение')),
                ('position1', models.BooleanField(default=False, verbose_name='положение центральное')),
                ('position2', models.BooleanField(default=False, verbose_name='картинка длинная внизу')),
            ],
            options={
                'verbose_name': 'Основные изображения',
                'verbose_name_plural': 'Основные изображения',
            },
        ),
    ]
