# Generated by Django 4.0.3 on 2022-07-25 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0005_alter_main_images_artimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Top_Models',
        ),
    ]
