# Generated by Django 4.0.3 on 2022-07-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0006_rename_articles_top_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='top_models',
            options={'verbose_name': 'Топ модели', 'verbose_name_plural': 'Топ модели'},
        ),
        migrations.RemoveField(
            model_name='top_models',
            name='image_central',
        ),
        migrations.RemoveField(
            model_name='top_models',
            name='main_article',
        ),
        migrations.AddField(
            model_name='top_models',
            name='show_art',
            field=models.BooleanField(default=False, verbose_name='Показать'),
        ),
        migrations.AddField(
            model_name='top_models',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='Мини-изображение'),
        ),
        migrations.AlterField(
            model_name='top_models',
            name='artimage',
            field=models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name=' основное изображение'),
        ),
        migrations.AlterField(
            model_name='top_models',
            name='full_text',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='top_models',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название модели'),
        ),
    ]
