# Generated by Django 4.0.3 on 2022-07-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0007_alter_top_models_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_models',
            name='artimage',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/top_models', verbose_name=' основное изображение'),
        ),
        migrations.AlterField(
            model_name='top_models',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/top_models', verbose_name='Мини-изображение'),
        ),
    ]
