# Generated by Django 4.0.3 on 2022-07-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0008_alter_top_models_artimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top_models',
            name='show_art',
        ),
        migrations.AddField(
            model_name='top_models',
            name='show_art1',
            field=models.BooleanField(default=False, verbose_name='Показать на 1 позици'),
        ),
        migrations.AddField(
            model_name='top_models',
            name='show_art2',
            field=models.BooleanField(default=False, verbose_name='Показать на 2 позици'),
        ),
        migrations.AddField(
            model_name='top_models',
            name='show_art3',
            field=models.BooleanField(default=False, verbose_name='Показать на 3 позици'),
        ),
        migrations.AddField(
            model_name='top_models',
            name='show_art4',
            field=models.BooleanField(default=False, verbose_name='Показать на 4 позици'),
        ),
        migrations.AddField(
            model_name='top_models',
            name='show_art5',
            field=models.BooleanField(default=False, verbose_name='Показать на 5 позици'),
        ),
        migrations.AddField(
            model_name='top_models',
            name='show_art6',
            field=models.BooleanField(default=False, verbose_name='Показать на 6 позици'),
        ),
        migrations.AddField(
            model_name='top_models',
            name='show_art7',
            field=models.BooleanField(default=False, verbose_name='Показать на 7 позици'),
        ),
        migrations.AddField(
            model_name='top_models',
            name='show_art8',
            field=models.BooleanField(default=False, verbose_name='Показать на 8 позици'),
        ),
    ]
