# Generated by Django 4.0.3 on 2022-07-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0010_top_models_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_models',
            name='price',
            field=models.CharField(max_length=50, null=True, verbose_name='Стоимость модели'),
        ),
    ]
