# Generated by Django 4.0.3 on 2022-07-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0011_alter_top_models_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название модели')),
                ('price', models.CharField(max_length=50, null=True, verbose_name='Стоимость модели')),
                ('full_text', models.TextField(verbose_name='описание')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('small_image', models.ImageField(blank=True, null=True, upload_to='static/img/top_models', verbose_name='Мини-изображение')),
                ('artimage', models.ImageField(blank=True, null=True, upload_to='static/img/top_models', verbose_name=' основное изображение')),
                ('show_item', models.BooleanField(default=False, verbose_name='Показать')),
            ],
            options={
                'verbose_name': 'Топ модели',
                'verbose_name_plural': 'Топ модели',
            },
        ),
    ]
