# Generated by Django 4.0.3 on 2022-07-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0012_all_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all_products',
            options={'verbose_name': 'Все товары', 'verbose_name_plural': 'Все товары'},
        ),
    ]
