# Generated by Django 4.0.3 on 2022-07-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0017_alter_top_models_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_models',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
