# Generated by Django 4.0.3 on 2022-08-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0019_alter_all_products_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50, verbose_name='Название модели')),
                ('price', models.CharField(max_length=50, null=True, verbose_name='Стоимость модели')),
                ('full_text', models.TextField(verbose_name='описание')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('small_image', models.ImageField(blank=True, null=True, upload_to='static/img/top_models', verbose_name='Мини-изображение')),
                ('artimage', models.ImageField(blank=True, null=True, upload_to='static/img/top_models', verbose_name=' основное изображение')),
                ('show_item', models.BooleanField(default=False, verbose_name='Показать')),
            ],
            options={
                'verbose_name': 'Apple',
                'verbose_name_plural': 'Apple',
            },
        ),
        migrations.CreateModel(
            name='Huawei',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50, verbose_name='Название модели')),
                ('price', models.CharField(max_length=50, null=True, verbose_name='Стоимость модели')),
                ('full_text', models.TextField(verbose_name='описание')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('small_image', models.ImageField(blank=True, null=True, upload_to='static/img/top_models', verbose_name='Мини-изображение')),
                ('artimage', models.ImageField(blank=True, null=True, upload_to='static/img/top_models', verbose_name=' основное изображение')),
                ('show_item', models.BooleanField(default=False, verbose_name='Показать')),
            ],
            options={
                'verbose_name': 'Huawei',
                'verbose_name_plural': 'Huawei',
            },
        ),
        migrations.CreateModel(
            name='Samsung',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50, verbose_name='Название модели')),
                ('price', models.CharField(max_length=50, null=True, verbose_name='Стоимость модели')),
                ('full_text', models.TextField(verbose_name='описание')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('small_image', models.ImageField(blank=True, null=True, upload_to='static/img/top_models', verbose_name='Мини-изображение')),
                ('artimage', models.ImageField(blank=True, null=True, upload_to='static/img/top_models', verbose_name=' основное изображение')),
                ('show_item', models.BooleanField(default=False, verbose_name='Показать')),
            ],
            options={
                'verbose_name': 'Samsung',
                'verbose_name_plural': 'Samsung',
            },
        ),
    ]
