# Generated by Django 4.0.3 on 2022-08-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0020_apple_huawei_samsung'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Samsung',
        ),
    ]
