# Generated by Django 4.0.3 on 2022-08-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0021_delete_samsung'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apple',
        ),
    ]
