# Generated by Django 4.0.3 on 2022-08-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0024_all_products_show_apple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_products',
            name='show_apple',
            field=models.BooleanField(default=False, verbose_name='Apple'),
        ),
    ]
