# Generated by Django 4.0.3 on 2022-08-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0026_all_products_show_huawei_all_products_show_samsung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_products',
            name='discount',
            field=models.CharField(max_length=10, null=True, verbose_name='Размер скидки'),
        ),
    ]
