# Generated by Django 4.0.3 on 2022-08-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0026_all_products_show_huawei_all_products_show_samsung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_models',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название моделиb'),
        ),
    ]
