# Generated by Django 4.0.3 on 2022-08-09 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0028_order_alter_top_models_title_orderposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
