# Generated by Django 4.0.3 on 2022-08-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0029_remove_all_products_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_products',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Скидка'),
        ),
    ]
