# Generated by Django 4.0.3 on 2022-08-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0030_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
