# Generated by Django 4.0.3 on 2022-08-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0030_all_products_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_products',
            name='sale',
            field=models.IntegerField(blank=True, default=0, verbose_name='Скидка в процентах'),
        ),
    ]
