# Generated by Django 4.0.3 on 2022-08-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0032_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_products',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
