# Generated by Django 4.0.3 on 2022-08-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0032_remove_all_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_products',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
