# Generated by Django 4.0.3 on 2022-08-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0035_remove_all_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_products',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
