# Generated by Django 4.0.3 on 2022-08-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0038_all_products_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_products',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='all_products',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
