# Generated by Django 4.0.3 on 2022-08-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0043_all_products_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_products',
            name='show_item',
            field=models.BooleanField(default=False, verbose_name='Наличие товара'),
        ),
    ]
