# Generated by Django 4.0.3 on 2022-08-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0045_all_products_show_honor'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_products',
            name='discount_active',
            field=models.BooleanField(default=False, verbose_name='Есть скидка?'),
        ),
    ]
