# Generated by Django 4.0.3 on 2022-08-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0033_all_products_slug'),
        ('mobiles', '0046_all_products_discount_active'),
    ]

    operations = [
    ]
