# Generated by Django 4.0.3 on 2022-08-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0047_merge_20220825_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderposition',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderposition',
            name='product',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderPosition',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
