# Generated by Django 4.0.3 on 2022-09-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0048_remove_orderposition_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_models',
            name='show_art9',
            field=models.BooleanField(default=False, verbose_name='Показать на 8 позици'),
        ),
    ]
