# Generated by Django 4.0.3 on 2022-09-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0049_top_models_show_art9'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top_models',
            name='show_art9',
        ),
    ]
