# Generated by Django 4.0.3 on 2022-12-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0050_remove_top_models_show_art9'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_products',
            name='show_on_main_page',
            field=models.BooleanField(default=False, verbose_name='Показать на главной странице'),
        ),
    ]
