# Generated by Django 4.0.3 on 2022-12-08 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0051_all_products_show_on_main_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top_models',
            name='show_art1',
        ),
        migrations.RemoveField(
            model_name='top_models',
            name='show_art2',
        ),
        migrations.RemoveField(
            model_name='top_models',
            name='show_art3',
        ),
        migrations.RemoveField(
            model_name='top_models',
            name='show_art4',
        ),
        migrations.RemoveField(
            model_name='top_models',
            name='show_art5',
        ),
        migrations.RemoveField(
            model_name='top_models',
            name='show_art6',
        ),
        migrations.RemoveField(
            model_name='top_models',
            name='show_art7',
        ),
        migrations.RemoveField(
            model_name='top_models',
            name='show_art8',
        ),
    ]
