# Generated by Django 4.0.3 on 2022-12-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0052_remove_top_models_show_art1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='top_models',
            options={},
        ),
    ]
