# Generated by Django 4.0.3 on 2022-12-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0053_alter_top_models_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top_models',
            name='artimage',
        ),
        migrations.RemoveField(
            model_name='top_models',
            name='date',
        ),
        migrations.RemoveField(
            model_name='top_models',
            name='full_text',
        ),
        migrations.RemoveField(
            model_name='top_models',
            name='price',
        ),
        migrations.RemoveField(
            model_name='top_models',
            name='small_image',
        ),
    ]
