# Generated by Django 4.0.3 on 2022-12-08 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0054_remove_top_models_artimage_remove_top_models_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Top_Models',
        ),
    ]
