# Generated by Django 4.0.3 on 2022-12-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0055_delete_top_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50, verbose_name='Название статьи')),
                ('full_text', models.TextField(verbose_name='описание')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('show_item', models.BooleanField(default=False, verbose_name='Показать статью')),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
