# Generated by Django 4.0.3 on 2022-12-13 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0056_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Статьи'},
        ),
    ]
