# Generated by Django 4.0.3 on 2022-12-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0057_alter_articles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Статьи', 'verbose_name_plural': 'Статьи'},
        ),
    ]
