# Generated by Django 4.0.3 on 2022-12-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0058_alter_articles_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/company', verbose_name='Логотип'),
        ),
    ]
