# Generated by Django 4.0.3 on 2022-12-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0059_articles_small_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='company_article',
            field=models.BooleanField(default=False, verbose_name='Статья про бренд'),
        ),
    ]
